# Generated by Django 5.0.6 on 2025-12-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Employee_No', models.IntegerField(primary_key=True, serialize=False)),
                ('Employee_Name', models.CharField(max_length=24)),
                ('Employee_Salary', models.IntegerField()),
            ],
        ),
    ]
