# Generated by Django 5.0.6 on 2025-12-26 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Department_No', models.IntegerField(primary_key=True, serialize=False)),
                ('Department_Name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DBAPP.department'),
        ),
    ]
