# Generated by Django 5.0.6 on 2025-12-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBAPP', '0002_department_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='Department_No',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
