# Generated by Django 5.0.6 on 2025-12-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBAPP', '0003_alter_department_department_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Images',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
