# Generated by Django 5.0.6 on 2025-12-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBAPP', '0007_alter_employee_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Images',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
