# Generated by Django 5.0.6 on 2026-01-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBAPP', '0010_alter_employee_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Images',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
